paths:
  raw: "data/raw/"
  proc: "data/proc/"

data:
  elections:
    fn: "1976-2020-house.csv"
    democrat: ["DEMOCRAT", "DEMOCRATIC-FARM-LABOR", "DEMOCRATIC-FARMER-LABOR", "DEMOCRATIC-NPL"]
    filters: ["special", "runoff", "unofficial", "fusion_ticket"]
